### ISSUE TITLE
can use p5 audio tools ?

### ISSUE THREAD

**Issue by odaymusic** [codeanticode/p5.dart#6] opened 2021-08-19 08:20 UTC
can use p5 audio tools ?

**Comment by codeanticode** [comment] 2021-08-25 14:11
Not sure, I think the main hurdle is that p5 libraries are written in Java, a different language from Dart. Some information in this reddit thread could be useful:

https://www.reddit.com/r/dartlang/comments/i6j0bi/can_i_add_a_jar_library_to_dart_and_flutter/

**Comment by aalex** [comment] 2021-09-09 21:25
In short: no.

**Comment by codeanticode** [comment] 2022-04-17 20:05
Duplicate of #3

**Closed** 2022-04-17 20:04 UTC
